# Generated by Django 2.1.1 on 2018-09-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronosticos', '0002_auto_20180927_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='hora',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='fecha',
            field=models.DateField(),
        ),
    ]
