# Generated by Django 2.1.1 on 2018-09-28 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pronosticos', '0004_auto_20180927_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaLiga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fecha_liga', to='pronosticos.Fecha')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liga_fecha', to='pronosticos.Liga')),
            ],
        ),
    ]
