# Generated by Django 2.1.1 on 2018-10-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pronosticos', '0008_liga_fechas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pronostico',
            name='puntos',
        ),
    ]
