# Generated by Django 2.1.1 on 2018-10-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronosticos', '0009_remove_pronostico_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronostico',
            name='resultado',
            field=models.IntegerField(default=0),
        ),
    ]
