# Generated by Django 2.1.1 on 2018-10-17 03:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pronosticos', '0010_pronostico_resultado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pronostico',
            unique_together={('user', 'partido')},
        ),
    ]
