# Generated by Django 2.1.1 on 2018-10-17 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pronosticos', '0011_auto_20181017_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigaTorneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liga_torneo', to='pronosticos.Liga')),
            ],
            options={
                'ordering': ('torneo',),
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_torneo', to=settings.AUTH_USER_MODEL)),
                ('ligas', models.ManyToManyField(through='pronosticos.LigaTorneo', to='pronosticos.Liga')),
            ],
        ),
        migrations.CreateModel(
            name='UserTorneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneo_user', to='pronosticos.Torneo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_torneo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('torneo',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='equipoliga',
            unique_together={('equipo', 'liga')},
        ),
        migrations.AlterUniqueTogether(
            name='fechaliga',
            unique_together={('fecha', 'liga')},
        ),
        migrations.AddField(
            model_name='torneo',
            name='users',
            field=models.ManyToManyField(through='pronosticos.UserTorneo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ligatorneo',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneo_liga', to='pronosticos.Torneo'),
        ),
        migrations.AlterUniqueTogether(
            name='usertorneo',
            unique_together={('torneo', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='ligatorneo',
            unique_together={('torneo', 'liga')},
        ),
    ]
